controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    arm_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    arm_effort_controller:
      type: effort_controllers/JointGroupEffortController

arm_controller:
  ros__parameters:
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

arm_velocity_controller:
  ros__parameters:
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

arm_effort_controller:
  ros__parameters:
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
